[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "OxRSE_training"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "flake8"]
